### ISSUE TITLE
Branding Assets Creation

### ISSUE THREAD

**Issue by KrashLeviathan** [hammer-io/yggdrasil#103]
We need to come up with a better set of branding assets for Hammer-IO. They should differentiate the different services, but also be consistent and complimentary to each other.

### At a minimum, we need to produce the following:

- Logos
  - Hammer-IO (should be covered already, but may need revisiting)
  - Tyr
  - Yggdrasil
  - Heimdall
  - Requirements:
    - Each should have a primary version (long horizontal orientation, including graphics and text) and a secondary version (square dimensions, probably just with graphic)
    - Each version should have small, medium, and large sizes
    - Each should have ~~jpeg and~~ png alternatives
    - Yggdrasil also needs a favicon (recommend using [www.favicon-generator.org](https://www.favicon-generator.org/).)
- Typography
  - Primary font, which should be something sans-serif
  - Secondary font to be used as headers or accents. Maybe something in italics or block letters.
- Color Pallete
  - Light and dark primary
  - Light and dark secondary
  - Accent color
  - Complementary greys, whites, and/or other neutrals
- A collection of icons
  - I have some viking ones already that we could use
  - Find a complementary set of general icons for menu buttons, arrows, etc (something like font-awesome)

### Other optional stuff that would be useful

- Patterns (could be used for backgrounds)
- Banner images

### Create and document

Save the files in the Google Drive share folder under the Branding Assets folder. Organize it so it's more manageable. If necessary, make a README.

**Comment by KrashLeviathan** [comment]
What I have left to do at this point:

- Logos
  - Hammer-IO
    - logo w/ text
  - Tyr
    - logo
    - logo w/ text
  - Yggdrasil
    - logo
    - logo w/ text
    -  favicon
  - Heimdall
    - logo
    - logo w/ text
  - Others...?
- Icons:  Find a complementary set of general icons for menu buttons, arrows, etc (something like font-awesome)
- Documentation if necessary

**Comment by jackcmeyer** [comment]
@KrashLeviathan icons should be taken care of, material-ui has their set of icons

**Comment by KrashLeviathan** [comment]
I created the wider logo with text, created text graphics for all current products, and created the favicon files. Everything is in the drive. Closing.
