### ISSUE TITLE
Login and Logout are broken

### ISSUE THREAD

**Issue by KrashLeviathan** [hammer-io/yggdrasil#141]
## Steps to Reproduce

1. Checkout master branch in project endor and pull down latest changes
2. `npm run initTestDB` to reset database
3. Start endor: `npm start`
4. Open Yggdrasil, and checkout / pull down latest master branch
5. Start Yggdrasil
6. Open `localhost:8080`, which takes you to login page
7. Enter user credentials for one of the test users (I've been using `jreach`). Page doesn't redirect, and there's an error message in the console
8. Refresh the page. Now it redirects to home??? So maybe the login worked but errored somewhere before redirecting
9. Signout of the application. It takes you to the login page.
10. Refresh the page without logging back in. You will be taken to the home dashboard. This time, it appears the redirect is working when you click "Sign Out", but it doesn't actually sign you out of the session.

**Comment by jackcmeyer** [comment]
This is due to not having a firebase account created since it didn't go through the new user setup. Closing this issue.
