### ISSUE TITLE
Set up react

### ISSUE THREAD

**Issue by jackcmeyer** [hammer-io/yggdrasil#2]
As a user, I want react to run the front end of yggdrasil.

**Comment by nischayv** [comment]
Some libraries and frameworks that we will need -

- http://www.material-ui.com/#/
- https://webpack.js.org/
- http://redux.js.org/

**Comment by nischayv** [comment]
@NathanDeGraaf @jackcmeyer Should this be closed??

**Comment by jackcmeyer** [comment]
@nischayv yes, I will close
