### ISSUE TITLE
Login after Logout fails

### ISSUE THREAD

**Issue by KrashLeviathan** [hammer-io/yggdrasil#202]
### Steps to Reproduce

1. Open the developer console in the browser
2. Sign out of whatever user you're using
3. Login as a different user. The login fails, and the following message is shown in the console:
```
code: "auth/user-not-found"
message: "There is no user record corresponding to this identifier. The user may have been deleted."
```
4. Refresh the page. The user is now logged in.

**Comment by nischayv** [comment]
Could this be related to firebase?
