### ISSUE TITLE
Improve Monitoring page and graph components

### ISSUE THREAD

**Issue by nischayv** [hammer-io/yggdrasil#207]
- Recent memory usage should have units on the graph (Time and Memory) and also in the pop up (MB, GB, etc). Also the numbers are too long. Change it based on the units used.
- Current Memory usage needs units. Graph doesn't mean much without units.
- Clicking on the space between the health bars in the heartbeat graph does nothing (Ideally this would be fine, but since the ratio of the amount of space to the amount of bars is quite high, I ended up clicking quite a few times on the spaces instead of the bars accidently when I was trying it out and it did nothing. Other times I clicked exactly on the bar and it worked. This gives a little janky feel to the UI). Perhaps making the closest bar (left or right) active when clicking on a space would be a decent solution.
- Change all graph colors to use material colors
- UI is not mobile "friendly". Doesn't have to be mobile friendly, but shouldn't break on a small device either. The Paper wrapper resizes, while some components don't below a certain screen size, causing the page to look weird. 
- Use colors from Theme.js instead of hardcoded values

**Comment by NathanDeGraaf** [comment]
Only thing I couldn't get added right now is the time labeling. I will either need to do annoying stuff with the current graphing library we're using or find a new one for those graphs. Therefore I'm kicking that down the road to a different issue.

**Comment by jackcmeyer** [comment]
@NathanDeGraaf Are you talking about converting a time stamp to a proper date/time?

**Comment by NathanDeGraaf** [comment]
I'm talking about getting the x-axis to display nice ticks showing the date

**Comment by jackcmeyer** [comment]
@NathanDeGraaf 👍 Awesome, open that PR!
