### ISSUE TITLE
Extra forward slashes in Connected Services links

### ISSUE THREAD

**Issue by KrashLeviathan** [hammer-io/yggdrasil#228]
For GitHub and Travis links (see screenshot below)

![screenshot from 2018-04-04 22-40-28](https://user-images.githubusercontent.com/8837587/38346224-4b45dab4-3859-11e8-95e3-ced4f4c216f3.png)

**Comment by KrashLeviathan** [comment]
The links should also open in a new tab (target=_blank)

**Comment by jackcmeyer** [comment]
This seems to be an issue on the server. The connected services are stored that way in the datatbase. @clarkerican any insight into why this is happening?
