### ISSUE TITLE
Request Server Space from ETG

### ISSUE THREAD

**Issue by KrashLeviathan** [hammer-io/yggdrasil#40]

**Comment by jackcmeyer** [comment]
Requested space on 11/25

**Comment by jackcmeyer** [comment]
11/27 Update: ETG says VM should be available tomorrow afternoon

**Comment by jackcmeyer** [comment]
11/27 afternoon update: ETG has completed request for server. I'll create users for everyone

**Comment by jackcmeyer** [comment]
usernames and password have been sent via slack.
